[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#110c03"
foreground = "#c3c2c0"

[colors.cursor]
text = "#110c03"
cursor = "#c3c2c0"

[colors.vi_mode_cursor]
text = "#110c03"
cursor = "#c3c2c0"

[colors.search.matches]
foreground = "#110c03"
background = "#c3c2c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#696255"
background = "#c3c2c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#110c03"
red = "#C33D22"
green = "#A15332"
yellow = "#CF5235"
blue = "#B06847"
magenta = "#DC6B4A"
cyan = "#D0704E"
white = "#c3c2c0"

[colors.bright]
black = "#696255"
red = "#C33D22"
green = "#A15332"
yellow = "#CF5235"
blue = "#B06847"
magenta = "#DC6B4A"
cyan = "#D0704E"
white = "#c3c2c0"

[colors.dim]
black = "#c3c2c0"
red = "#C33D22"
green = "#DC6B4A"
yellow = "#CF5235"
blue = "#B06847"
magenta = "#A15332"
cyan = "#D0704E"
white = "#696255"
