[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#111313"
foreground = "#c3c4c4"

[colors.cursor]
text = "#111313"
cursor = "#c3c4c4"

[colors.vi_mode_cursor]
text = "#111313"
cursor = "#c3c4c4"

[colors.search.matches]
foreground = "#111313"
background = "#c3c4c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a6e6e"
background = "#c3c4c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#111313"
red = "#95662D"
green = "#897565"
yellow = "#7E8376"
blue = "#A9822C"
magenta = "#978877"
cyan = "#B3A38C"
white = "#c3c4c4"

[colors.bright]
black = "#5a6e6e"
red = "#95662D"
green = "#897565"
yellow = "#7E8376"
blue = "#A9822C"
magenta = "#978877"
cyan = "#B3A38C"
white = "#c3c4c4"

[colors.dim]
black = "#c3c4c4"
red = "#95662D"
green = "#978877"
yellow = "#7E8376"
blue = "#A9822C"
magenta = "#897565"
cyan = "#B3A38C"
white = "#5a6e6e"
