[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10 

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#121314"
foreground = "#c3c4c4"

[colors.cursor]
text = "#121314"
cursor = "#c3c4c4"

[colors.vi_mode_cursor]
text = "#121314"
cursor = "#c3c4c4"

[colors.search.matches]
foreground = "#121314"
background = "#c3c4c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a646f"
background = "#c3c4c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#121314"
red = "#756E67"
green = "#916737"
yellow = "#8E6F4E"
blue = "#867B70"
magenta = "#938577"
cyan = "#C58F47"
white = "#c3c4c4"

[colors.bright]
black = "#5a646f"
red = "#756E67"
green = "#916737"
yellow = "#8E6F4E"
blue = "#867B70"
magenta = "#938577"
cyan = "#C58F47"
white = "#c3c4c4"

[colors.dim]
black = "#c3c4c4"
red = "#756E67"
green = "#938577"
yellow = "#8E6F4E"
blue = "#867B70"
magenta = "#916737"
cyan = "#C58F47"
white = "#5a646f"
