[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10 

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#0D1011"
foreground = "#c2c3c3"

[colors.cursor]
text = "#0D1011"
cursor = "#c2c3c3"

[colors.vi_mode_cursor]
text = "#0D1011"
cursor = "#c2c3c3"

[colors.search.matches]
foreground = "#0D1011"
background = "#c2c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#58656c"
background = "#c2c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0D1011"
red = "#3B5D67"
green = "#566361"
yellow = "#A02708"
blue = "#B9622F"
magenta = "#C59463"
cyan = "#587B84"
white = "#c2c3c3"

[colors.bright]
black = "#58656c"
red = "#3B5D67"
green = "#566361"
yellow = "#A02708"
blue = "#B9622F"
magenta = "#C59463"
cyan = "#587B84"
white = "#c2c3c3"

[colors.dim]
black = "#c2c3c3"
red = "#3B5D67"
green = "#C59463"
yellow = "#A02708"
blue = "#B9622F"
magenta = "#566361"
cyan = "#587B84"
white = "#58656c"
