[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10 

[font.normal]
family='Mononoki Nerd Font'
style="bold"

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Victor Mono'
style='Bold Italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && export ZSH_ISOLATE=0 && zsh"]
[colors.primary]
background = "#0c0e0f"
foreground = "#c2c2c3"

[colors.cursor]
text = "#0c0e0f"
cursor = "#c2c2c3"

[colors.vi_mode_cursor]
text = "#0c0e0f"
cursor = "#c2c2c3"

[colors.search.matches]
foreground = "#0c0e0f"
background = "#c2c2c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#58626b"
background = "#c2c2c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0c0e0f"
red = "#3E5C61"
green = "#485751"
yellow = "#5A6C67"
blue = "#7A8171"
magenta = "#677D82"
cyan = "#758A8F"
white = "#c2c2c3"

[colors.bright]
black = "#58626b"
red = "#3E5C61"
green = "#485751"
yellow = "#5A6C67"
blue = "#7A8171"
magenta = "#677D82"
cyan = "#758A8F"
white = "#c2c2c3"

[colors.dim]
black = "#c2c2c3"
red = "#3E5C61"
green = "#677D82"
yellow = "#5A6C67"
blue = "#7A8171"
magenta = "#485751"
cyan = "#758A8F"
white = "#58626b"
