[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10 

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#0b0d0a"
foreground = "#c2c2c1"

[colors.cursor]
text = "#0b0d0a"
cursor = "#c2c2c1"

[colors.vi_mode_cursor]
text = "#0b0d0a"
cursor = "#c2c2c1"

[colors.search.matches]
foreground = "#0b0d0a"
background = "#c2c2c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#606956"
background = "#c2c2c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b0d0a"
red = "#215161"
green = "#B6610F"
yellow = "#7A827B"
blue = "#BC8F5B"
magenta = "#216C88"
cyan = "#4B7B8C"
white = "#c2c2c1"

[colors.bright]
black = "#606956"
red = "#215161"
green = "#B6610F"
yellow = "#7A827B"
blue = "#BC8F5B"
magenta = "#216C88"
cyan = "#4B7B8C"
white = "#c2c2c1"

[colors.dim]
black = "#c2c2c1"
red = "#215161"
green = "#216C88"
yellow = "#7A827B"
blue = "#BC8F5B"
magenta = "#B6610F"
cyan = "#4B7B8C"
white = "#606956"
