[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10 

[font.normal]
family='Mononoki Nerd Font'
style="bold"

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Victor Mono'
style='Bold Italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && export ZSH_ISOLATE=0 && zsh"]
[colors.primary]
background = "#020A19"
foreground = "#bfc1c5"

[colors.cursor]
text = "#020A19"
cursor = "#bfc1c5"

[colors.vi_mode_cursor]
text = "#020A19"
cursor = "#bfc1c5"

[colors.search.matches]
foreground = "#020A19"
background = "#bfc1c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#575e6b"
background = "#bfc1c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#020A19"
red = "#0C32E3"
green = "#2558C6"
yellow = "#144EF9"
blue = "#2154EF"
magenta = "#146DFE"
cyan = "#2E6EFD"
white = "#bfc1c5"

[colors.bright]
black = "#575e6b"
red = "#0C32E3"
green = "#2558C6"
yellow = "#144EF9"
blue = "#2154EF"
magenta = "#146DFE"
cyan = "#2E6EFD"
white = "#bfc1c5"

[colors.dim]
black = "#bfc1c5"
red = "#0C32E3"
green = "#146DFE"
yellow = "#144EF9"
blue = "#2154EF"
magenta = "#2558C6"
cyan = "#2E6EFD"
white = "#575e6b"
