[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 10

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#0a0a0a"
foreground = "#c1c1c1"

[colors.cursor]
text = "#0a0a0a"
cursor = "#c1c1c1"

[colors.vi_mode_cursor]
text = "#0a0a0a"
cursor = "#c1c1c1"

[colors.search.matches]
foreground = "#0a0a0a"
background = "#c1c1c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#685555"
background = "#c1c1c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0a0a"
red = "#921D35"
green = "#B1314B"
yellow = "#B44A60"
blue = "#C8546C"
magenta = "#D27588"
cyan = "#7C8482"
white = "#c1c1c1"

[colors.bright]
black = "#685555"
red = "#921D35"
green = "#B1314B"
yellow = "#B44A60"
blue = "#C8546C"
magenta = "#D27588"
cyan = "#7C8482"
white = "#c1c1c1"

[colors.dim]
black = "#c1c1c1"
red = "#921D35"
green = "#D27588"
yellow = "#B44A60"
blue = "#C8546C"
magenta = "#B1314B"
cyan = "#7C8482"
white = "#685555"
